name: Testnet Test

on:
  schedule:
    # At 18:40 on every 4th day-of-week
    # https://crontab.guru
    - cron: "40 18 * * */4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Update env
        run: echo "PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"" > .env
      - name: Test
        run: npm run testnet
